### ISSUE TITLE
Fun calls with kwargs, starargs

### ISSUE THREAD

**Issue by daviis** [daviis/PyDucker#43]
We need to handle if/when a function has optional parameters. Ex range(end), range(start, end), range(start, end, step)

**Comment by JakeAlbee** [comment]
Just a note on this, I'm not sure if it has been looked at in awhile (I think it was covered) but any optional parameters that I found, for example for slicing, it would just throw a None value into an unused optional slot and we can just check if each spot has a value.

**Comment by JakeAlbee** [comment]
@daviis You implemented visit_Call, right?
