### ISSUE TITLE
UnitTest Correct/collections.py is broken

### ISSUE THREAD

**Issue by daviis** [daviis/PyDucker#84]
The unit test listed above isn't functional yet. Line 28 is the cause of an exception. It has to deal with dictionaries not needed to be sliced into with numbers instead any hashable type will work.

Todo: set up the VarBean.valType use in the walker.

**Comment by Smokebird** [comment]
To test this issue in Collections.py i have created a branch called collections. When testing this file no exception was thrown on line 28. Not for sure why an exception was not thrown on line 28 but it does seem that VarBean.valType has been set up a bit in Visit_Dict.

**Comment by daviis** [comment]
Yep, I agree that it is successfully taking the type out of the dictionary correctly. I'm not sure when this got fixed but it looks fine.
