### ISSUE TITLE
Scoping and funs not working correctly it seems

### ISSUE THREAD

**Issue by JakeAlbee** [daviis/PyDucker#97]
As I was testing the docStringParser updates I had to run a simple file but it said it was an IncorrectMethodException. File is as follows

```
def test(listOne):
    """
    @listOne:*int,str
    """
    print('do stuff')
x = [1,2,'a','b']    
test(x)

**Comment by daviis** [comment]
Are we handling non homogeneous collections yet?

**Comment by JakeAlbee** [comment]
It isn't related to non homogeneous collections, it throws this error

```
Exceptions.IncorrectMethodException: 
	On line: 7
	Can not find method: test
	In class: $funs
	With args: list

**Comment by daviis** [comment]
Has to do with the problem of handling non homogeneous lists
